#All parameters required for to run metricbeat and prometheus properly.

- module: prometheus
  period: 10s
  hosts: ["localhost:80"]
  metrics_path: /metrics
  #Poniżej filtrujemy tylko jvm_memory_pool
  metrics_filters:
    include: ["jvm_memory_pool_*"]
    exclude: []

#Below Example of a different endpoint
- module: prometheus
  period: 10s
  hosts: ["localhost:80"]
  metrics_path: /metrics/gc