#below example of adjusted config for metricbeat.yml, most of the things come with defaults out-of-the-box. 
#Required changes are only for IP of Kibana and Elasticsearch. 


metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
setup.kibana:
  host: "http://{KibanaIPHere}:5601"
output.elasticsearch:
  hosts: ["{ElasticsearchIpHere}:9200"]
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~